version: '3.9'
services:
  nginx:  
    container_name: nginx
    hostname: nginx
    image: nginx:latest
    environment:
      - SERVICENAME=nginx
      - VERSION=docker
      - TZ=Africa/Johannesburg
      - PGID=1000
      - PUID=1000
      - DOMAIN=docker.local
      - VIRTUAL_HOST=nginx.docker.local
    ports:
      - 80:80
	  - 443:443
    volumes:
      - type: bind
        source: /docker/theforce/configs/nginx/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: /docker/theforce/configs/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: /docker/theforce/data/nginx/certbot
        target: /var/www/certbot
      - type: bind
        source: /docker/theforce/configs/nginx/conf
        target: /etc/certbot/conf		
      - type: bind
        source: /docker/theforce/data/nginx/letsencrypt/letsencrypt-site
        target: /usr/share/nginx/html
      - type: bind
        source: /docker/theforce/data/nginx/letsencrypt/acme_challenge
        target: /var/www/challenge/.well-known/acme-challenge
    restart: always
	

	
	

#certonly --webroot \
#--register-unsafely-without-email --agree-tos \
#--webroot-path=/data/letsencrypt \
#--staging \
#-d ohhaithere.com -d www.ohhaithere.com

#certbot/certbot \
#--staging \
#certificates

#certonly --webroot \
#--email youremail@domain.com --agree-tos --no-eff-email \
#--webroot-path=/data/letsencrypt \
#-d ohhaithere.com -d www.ohhaithere.com